import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Markfy Development",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}